#!/usr/bin/env node
/**
 * memory-save.js — Persistent memory for GitHub Copilot
 *
 * Zero external dependencies. Pure Node.js built-ins only.
 * Enterprise-safe: all data stays in the repo, no external calls.
 *
 * Usage:
 *   node scripts/memory-save.js                    # interactive mode
 *   node scripts/memory-save.js --preference "..."  # save a preference
 *   node scripts/memory-save.js --decision "..." --reason "..."
 *   node scripts/memory-save.js --pattern "..." --file "src/..."
 *   node scripts/memory-save.js --session "..."     # log session note
 *   node scripts/memory-save.js --rebuild           # regenerate memory block in copilot-instructions.md
 *   node scripts/memory-save.js --show              # print current memory
 */

'use strict'

const fs = require('fs')
const path = require('path')
const readline = require('readline')

// ── Paths ─────────────────────────────────────────────────────────────────────

const ROOT = path.resolve(__dirname, '..')
const MEMORY_DIR = path.join(ROOT, '.github', 'memory')
const INSTRUCTIONS = path.join(ROOT, '.github', 'copilot-instructions.md')

const FILES = {
  preferences: path.join(MEMORY_DIR, 'user-preferences.md'),
  decisions:   path.join(MEMORY_DIR, 'project-decisions.md'),
  patterns:    path.join(MEMORY_DIR, 'known-patterns.md'),
  session:     path.join(MEMORY_DIR, 'session-log.md'),
}

const MEMORY_START = '<!-- MEMORY:START -->'
const MEMORY_END   = '<!-- MEMORY:END -->'

// ── Date helpers ──────────────────────────────────────────────────────────────

function today() {
  return new Date().toISOString().slice(0, 10)
}

function nowHHMM() {
  return new Date().toISOString().slice(0, 16).replace('T', ' ')
}

// ── File helpers ──────────────────────────────────────────────────────────────

function readFile(p) {
  return fs.existsSync(p) ? fs.readFileSync(p, 'utf8') : ''
}

function appendLine(file, line) {
  const content = readFile(file)
  fs.writeFileSync(file, content.trimEnd() + '\n' + line + '\n', 'utf8')
}

// ── Memory operations ─────────────────────────────────────────────────────────

function savePreference(text) {
  appendLine(FILES.preferences, `- [${today()}] ${text}`)
  console.log(`Saved preference: ${text}`)
}

function saveDecision(text, reason) {
  const line = reason
    ? `- [${today()}] ${text} | Reason: ${reason}`
    : `- [${today()}] ${text}`
  appendLine(FILES.decisions, line)
  console.log(`Saved decision: ${text}`)
}

function savePattern(text, file) {
  const line = file
    ? `- [${today()}] ${text} (file: ${file})`
    : `- [${today()}] ${text}`
  appendLine(FILES.patterns, line)
  console.log(`Saved pattern: ${text}`)
}

function saveSession(note) {
  const header = `\n## ${nowHHMM()}`
  const line = `- ${note}`
  const content = readFile(FILES.session)
  fs.writeFileSync(FILES.session, content.trimEnd() + '\n' + header + '\n' + line + '\n', 'utf8')
  console.log(`Logged session note: ${note}`)
}

// ── Rebuild memory block in copilot-instructions.md ───────────────────────────

function extractEntries(file, maxLines = 10) {
  const content = readFile(file)
  return content
    .split('\n')
    .filter(l => l.match(/^- \[/))
    .slice(-maxLines) // most recent N entries
    .join('\n')
}

function extractSessionLog(maxEntries = 5) {
  const content = readFile(FILES.session)
  const blocks = content.split(/\n## /).filter(Boolean)
  return blocks.slice(-maxEntries).map(b => '## ' + b.trim()).join('\n\n')
}

function buildMemoryBlock() {
  const prefs    = extractEntries(FILES.preferences, 15)
  const decisions = extractEntries(FILES.decisions, 10)
  const patterns  = extractEntries(FILES.patterns, 10)
  const sessions  = extractSessionLog(3)

  const parts = []
  if (prefs)     parts.push(`### User Preferences\n${prefs}`)
  if (decisions) parts.push(`### Project Decisions\n${decisions}`)
  if (patterns)  parts.push(`### Known Patterns\n${patterns}`)
  if (sessions)  parts.push(`### Recent Sessions\n${sessions}`)

  if (!parts.length) return null

  return [
    MEMORY_START,
    '',
    '## Project Memory',
    '<!-- Auto-generated by scripts/memory-save.js — commit this block -->',
    '',
    parts.join('\n\n'),
    '',
    MEMORY_END,
  ].join('\n')
}

function rebuildInstructions() {
  const block = buildMemoryBlock()
  let content = readFile(INSTRUCTIONS)

  // Remove existing block
  const startIdx = content.indexOf(MEMORY_START)
  const endIdx   = content.indexOf(MEMORY_END)
  if (startIdx !== -1 && endIdx !== -1) {
    content = content.slice(0, startIdx).trimEnd() + '\n' + content.slice(endIdx + MEMORY_END.length)
  }

  // Append new block (or nothing if empty)
  if (block) {
    content = content.trimEnd() + '\n\n' + block + '\n'
    fs.writeFileSync(INSTRUCTIONS, content, 'utf8')
    console.log('Rebuilt memory block in copilot-instructions.md')
  } else {
    fs.writeFileSync(INSTRUCTIONS, content.trimEnd() + '\n', 'utf8')
    console.log('Memory is empty — cleared memory block.')
  }
}

// ── Show ──────────────────────────────────────────────────────────────────────

function show() {
  console.log('\n=== Preferences ===')
  console.log(extractEntries(FILES.preferences, 20) || '(none)')
  console.log('\n=== Project Decisions ===')
  console.log(extractEntries(FILES.decisions, 20) || '(none)')
  console.log('\n=== Known Patterns ===')
  console.log(extractEntries(FILES.patterns, 20) || '(none)')
  console.log('\n=== Recent Sessions ===')
  console.log(extractSessionLog(5) || '(none)')
}

// ── Interactive mode ──────────────────────────────────────────────────────────

async function interactive() {
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout })
  const q  = (prompt) => new Promise(resolve => rl.question(prompt, resolve))

  console.log('\nCopilot Memory Save')
  console.log('What type of memory? [p]reference / [d]ecision / [k]nown pattern / [s]ession log / [r]ebuild\n')

  const type = (await q('> ')).trim().toLowerCase()

  if (type === 'p' || type === 'preference') {
    const text = await q('Preference: ')
    if (text.trim()) savePreference(text.trim())
  } else if (type === 'd' || type === 'decision') {
    const text   = await q('Decision: ')
    const reason = await q('Reason (optional): ')
    if (text.trim()) saveDecision(text.trim(), reason.trim())
  } else if (type === 'k' || type === 'pattern') {
    const text = await q('Pattern description: ')
    const file = await q('File location (optional): ')
    if (text.trim()) savePattern(text.trim(), file.trim())
  } else if (type === 's' || type === 'session') {
    const text = await q('Session note: ')
    if (text.trim()) saveSession(text.trim())
  } else if (type === 'r' || type === 'rebuild') {
    rebuildInstructions()
    rl.close()
    return
  } else {
    console.log('Unknown type.')
    rl.close()
    return
  }

  rl.close()
  rebuildInstructions()
}

// ── CLI arg parsing ───────────────────────────────────────────────────────────

const args = process.argv.slice(2)

function getArg(flag) {
  const i = args.indexOf(flag)
  return i !== -1 ? args[i + 1] : null
}

if (args.includes('--show')) {
  show()
} else if (args.includes('--rebuild')) {
  rebuildInstructions()
} else if (args.includes('--preference')) {
  const text = getArg('--preference')
  if (text) { savePreference(text); rebuildInstructions() }
} else if (args.includes('--decision')) {
  const text   = getArg('--decision')
  const reason = getArg('--reason') || ''
  if (text) { saveDecision(text, reason); rebuildInstructions() }
} else if (args.includes('--pattern')) {
  const text = getArg('--pattern')
  const file = getArg('--file') || ''
  if (text) { savePattern(text, file); rebuildInstructions() }
} else if (args.includes('--session')) {
  const text = getArg('--session')
  if (text) { saveSession(text); rebuildInstructions() }
} else {
  // Interactive
  interactive().catch(console.error)
}
